#+TITLE: Emacs for Everyday People.
#+DATE:  <2020-08-11 Tue>
#+options: toc:nil
---
title: Slides for Emacs for Everyday People.
description: A video explaining why someone would want to use Emacs for writing!
---
* Title Slide
*Emacs for Everyone*

In this video I will cover:
1. What is Emacs?
2. Why use Emacs over other software?
* Slide: Quote
*Quote*

 "You do not rise to the level of your goals. You fall to the level of your systems" - James Clear, /Atomic Habits/
* Slide: What is Emacs
*What is Emacs*

+ Emacs is a "Lisp Interpreter"!
+ The main feature of Emacs is text-editing
+ People  are able to write code to
  create *packages*, adding a lot of
  functionality to Emacs!
+ *You don't need to program to use Emacs*
* Slide: Why Emacs?
*Why Emacs?*

1) Because Emacs is, in my opinion, a better system for writing than say, Microsoft Word
   + That is, if you know how to use it!
2) Because it is free!
   + Free as in Freedom
   + Free as in Monetary
   + Free as in Free Time! (*)
     - There's an upfront cost of time
     - But in the long run you save time.
* Slide: Editing Styles
*Editing Styles*

There are two primary editing styles that allows you to write text on a computer faster.
These are:
** Vim
Vim focuses on *Modal* editing. It's main philosophy is that most of the time
when writing text, you are actually *editing* rather than writing. Vim makes
editing a lot easier by splitting actions into different *modes*. These modes are:
1. Normal - the mode for describing actions to text
2. Insert - the mode for inserting text
3. Visual - the mode for selecting text
** Emacs
Emacs, the other hand, focuses on *Macros*, predefined actions that activates
when you press a certain sequence of keys. For example =C-n= allows me to move
down a line(without the arrow keys), and =C-p= allows me to move up one line.
This is useful because you are in one state all the time and it doesn't break
your editing flow. Binding your =Ctrl= key to =Caps-lock= makes the Emacs
bindings more ergonomic.
* Slide: What else can you do with Emacs?
*What else can you do with Emacs?*

 Most of my computer-related tasks are in Emacs! I use Emacs for:
1) Todo Lists - Basically manages my life
2) Writing Papers/Presentations
3) Writing Code
4) RSS reader(for blogs/youtube-videos)
5) Reading/Sending Emails
6) And much more!
* Closing
*Closing*

In the following videos, I plan to show you a lot of what you can do with Emacs, primarily
** More information:
- Learn more about [[https://www.gnu.org/software/emacs/][Emacs]].
- Read the [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org][Getting started with Doom-Emacs]] guide
- Read the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/index.html][Emacs manual]] and the [[https://orgmode.org/manual/index.html][org-mode manual]]. Personally never read it.. :D
  - You can also check out the manual within Emacs by pressing =SPC h i= and clicking on
    the topics that you want to know more about(or use your vim-keys(you can go
    to the next page of a manual by doing =C-j= or =C-k=, =C= stands for Control,
    =M= stands for "meta" or "alt")
- Before installing Doom Emacs(or after), check out my Overview of Emacs and my Evil-tutor
  walkthrough on why you should even bother with it!
