---
title: Emacs installation guide
description: In this post, I'll be showing you how Emacs can change your life, even if you're not a programmer
---
* Preface
This is an installation guide to Emacs, you can look at my other posts
to get an idea of what Emacs is and how you could use it to improve your life!
* Terminal Basics
Knowing the terminal is necessary for installing Emacs. After you
install Emacs, you aren't forced to use the terminal anymore(other than doing
=doom sync=). Don't be scared of the terminal! It's just a different way of
interacting with your computer!
** A tldr of how to use the terminal
When you open up your terminal(like in my Emacs installation vid in Windows), you'll see something like this:
#+BEGIN_SRC sh
~ $
#+END_SRC
The =~= stands for your home directory(which in MacOS, is something like
=/home/username= for Windows, watch my vid). The prompt is telling you that it's
currently waiting for commands in your home folder(aka directory). Typing
something on your keyboard will insert text right after the dollar sign! Another
name for "Terminal" is the "Command prompt", because the terminal is waiting for
you to type a command(a name of a program). For example typing:
#+BEGIN_SRC sh
~ $ ls
#+END_SRC
and pressing =Enter=, will show you all the directories(folders) in your home directory.

Terminal commands can also take arguments! This is similar to say, basic
grammar(I suck at grammar, so this analogy might be bad, sorry, English second
language). The terminal command is like the action verb(what you want to do),
and the arguments are like nouns(the object you're doing the action to))! Doing
something like:
#+BEGIN_SRC sh
~ $ cd Documents
#+END_SRC
translates to: "Change the current directory to Documents". In other words,
instead of right clicking a folder in a file explorer, you use commands to do
stuff to folders/files. The most commands are mnemonic, making remembering them
not too difficult.

These are the most important commands:
1. =ls= - Lists all the directories in your current folder
2. =cd <insert directory name here>= - "Change directory" moves you into another
   directory, just like clicking on a folder would with Finder or Windows Files
   explorer
Other than that, you basically just copy and paste in commands, one by one, like
I did in the installation video!

** Oher terminal concepts
In my installation guide, I refered to the =PATH= variable. That's basically
where terminal(or to be specific, your shell) will look for programs!
Programs(like =cd= and =ls=) are really just files that takes text based
arguments(think of them like functions from math)! Doing something like
#+BEGIN_SRC sh
~ $ ./.emacs.d/bin/doom sync
#+END_SRC
* Package Managers
Package managers are a program that helps you install other programs(packages).
The reason why programs are sometimes called "packages" is because certain
programs depend on other programs. The package managers job is to get the
necessary parts for running the program, which makes installing programs easy!

There are two package managers that I'll be using, depending if you're on MacOS or Windows:
1. Brew - MacOS
2. Scoop - Windows

Even though they are different, the concept is essentially the same! You can
install any program(that's available in their repositories) using just
one(sometimes more, but most of the time one) command! For example, I can
install discord using:

#+BEGIN_SRC sh
# Adds the bucket that contains discord
scoop bucket add extras
# installs discord
scoop install discord
#+END_SRC
* Emacs installation guide
Take a look below the video for more information! I made a small mistake in my video
and didn't make you install =llvm=. Also do =scoop install llvm= (it worked
without llvm, but install it just in case..).
#+HTML:<div class="resp-container mb-4 max-w-sm lg:max-w-none"><iframe class="resp-iframe" src="https://www.youtube.com/embed/f8TGLVveDaQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
** A summary of the installation process.
What you are going to be doing to install Emacs is first by installing a package
manager, which is a piece of software that allows you to install "packages"(or
Apps) using the command-line. You can find more information about the package
manager you'll be installing in your Operating System. Most of the time, you
should probably never do things that you don't understand, especially on your
computer! Get a rough understanding at what a package manager does, and what
I'm doing in these steps I gave you.
** Installing on MacOS
Here's Doom's official guide to install Emacs: [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-macos][Install Emacs]]

Here's a similar video/guide to installing Emacs on MacOs: [[https://www.youtube.com/watch?v=hCNOB5jjtmc][Installing and
getting started with Spacemacs: Emacs tutorial - YouTube]]. Sidenote: The video I
referenced shows how to install =Spacemacs=, which is similar to =Doom= but not
quite. I prefer Doom because it's less bloated(meaning it runs faster) and
doesn't add too much overhead to configuring. You could try out Spacemacs too,
to see if you like it! My guides should be useful for whatever
distribution(configuration really) of Emacs you are using!

Text guide:
Unfortunately my Mac broke([[https://www.youtube.com/user/rossmanngroup][Louis Rossmann - YouTube]]), so I can't show you the
installation in video. I will leave text instructions here for installing on
MacOS. You can install on MacOS using a similar process to what I showed in the
video, but Emacs should work a lot better on MacOS because it's a UNIX based
system. The main difference to the installation process is that rather than
using the =scoop= package manager, you would use [[https://brew.sh/][Homebrew]]. You can install
homebrew by opening your Terminal application(search for it using the MacOS app
search bar) and typing these lines in(one at a time) and press =Enter=.
#+BEGIN_SRC sh
# This line is a comment. The next line is the command to install the Homebrew Package manager
# You might have to enter your password. Make sure you're the admistrator on your system.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# Make sure to press ENTER, and wait for the installation to finish
# Type this line in, and press ENTER. Wait for installation to finish, and voila!
# required dependencies
brew install git ripgrep
# optional dependencies
brew install coreutils fd
# Installs clang
xcode-select --install

# Installs Emacs
brew tap d12frosted/emacs-plus
brew install emacs-plus
ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app

# These commands will install Doom Emacs!
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+END_SRC

The first command will run this [[https://raw.githubusercontent.com/Homebrew/install/master/install.sh][script]]. Look over the script to get a rough idea
at what the script is doing. The other commands just installs all the necessary
software required to install =Doom Emacs=.
** Windows Installation
If you don't want to use scoop, try [[https://chocolatey.org/install][Chocolatey]]. Scoop's just a little easier to
install(one less step). You can also not use a package manager(if you can't for
some reason) by downloading [[https://gitforwindows.org/][git]] and following these [[https://earvingad.github.io/posts/doom_emacs_windows/][instructions]]. I've installed
Emacs using all three of these options, ask me for help if needed. More (on the
Scoop installation process) in the video! A step by step guide is:
1. Install the [[https://github.com/lukesampson/scoop][Scoop]] package manager.
   1. Open up PowerShell
   2. Type the following commands. into powershell. NOTE: You can find out more
      about execution policies [[https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7][here]] and about the script that you'll about to be
      running [[https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1][here(you don't have to read/understand this script, but it's good
      practice to)]]
     #+BEGIN_SRC powershell
# This line is a comment. Type the next line into Powershell.
# Find out more about execution policies here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
# This installs the scoop package manager
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      #+END_SRC
2. Install by typing the following line into your shell!
   #+BEGIN_SRC sh
# This command installs git(use in powershell)
scoop install git
# Use git-bash(open it up, like in the video) to install emacs
# This installs Emacs and Doom's required programs. Install git before Emacs so it installs faster!
# I forgot to install llvm in the video, make sure you install it anyways

# adds the "extras" bucket
scoop bucket add extras
scoop install emacs ripgrep fd llvm
   #+END_SRC
3. Change your environment variables! (Check 25:50 in the video.)
4. Install Doom-emacs
   #+BEGIN_SRC sh
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
# This might take a while.
~/.emacs.d/bin/doom install
   #+END_SRC
* Installing Extra Programs(latex + Anki)
#+HTML: <div class="resp-container mb-4 max-w-sm lg:max-w-none"><iframe class="resp-iframe" src="https://www.youtube.com/embed/aV0BkzGsaTk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
** MacOS
*** Latex
There are two options that you can do to install Latex on MacOS. The first one
is a little more involved, but saves a lot of disk space. The second one will
take up 3GB of disk space, and installs a lot of stuff(like a latex editor, you
don't need this because you're already using Emacs!) that you don't need! I will
give you these two options and let you choose.
**** Option 1
Latex has its own package manager(just like your OS and Emacs). If you install
=basictex=, some packages might not be installed. The first time I exported to
pdf on Windows, Doom Emacs actually went out and installed these packages for
me! However, I am not sure if it'll do that for MacOS too. If it doesn't, the
first time you export to PDF, it'll give you an error message. You don't need to
worry! Just do =SPC b B= and type in =pdf latex output= (you're navigating to
that buffer) and press enter. You should see something along the lines of
=<insert package name here>.sty= is missing. You can install the missing package
using =tlmgr install <insert-package-name-here>=. Look at the 2:10 mark on the
video for a visual representation of what you'll be doing!
#+BEGIN_SRC sh
brew cask install basictex
# use tlmgr to install the missing latex packages
tlmgr install <package-name>
#+END_SRC
**** Option 2
Install Mactex. This(in theory) should have all the latex packages that you need(and a
lot more you don't need). If you something is missing, install it with tlmgr
with instructions from Option 1.
#+BEGIN_SRC sh
brew cask install mactex
#+END_SRC
*** Anki
#+BEGIN_SRC sh
brew install anki
#+END_SRC
** Windows
Stuff might take a while, but be patient!
#+BEGIN_SRC sh
scoop install latex anki
#+END_SRC
** Note on spellchecking
Emacs uses external programs to do spell checking! There are plenty of options,
but =aspell= is the default. =aspell= has a limited amount of words, so some
words that are correct but not used much might not be there. =ispell= is the
successor to =aspell= and works better, but the setup is a little more
involved(you have to add more lines to your config). Don't worry about this for
now, I'll show you how to get the best setup in a video later!

You can enable the =spell= module in your =init.el= (I showed similar things in
the video). Then do:
#+BEGIN_SRC sh
# if you're on MacOS. You can also install hunspell, but idk the difference between them
brew install aspell
# if you're in Windows
scoop install aspell
#+END_SRC
* Closing
#+HTML: <p> If something doesn't work, let me know! You can find my contact info in my <span><a href="/contact.html">contact</a></span> page </p>
